### ISSUE TITLE
setup RCNN failure

### ISSUE THREAD

**Issue by benjaminwfriedman** [bcmi/GracoNet-Object-Placement#14]
Hi All, 

Having issues runing the `python setup.py build develop` step in the setup. 

I have cuda 10.2 install on windows 10 running python 3.6 in cuda with the proper torch version. Have visual c build tools 2019 install which looks to be compatible with cude 10.2 and pytorch. However I receive the following errors on the command. 

```

Traceback (most recent call last):
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\torch\utils\cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\Cython\Distutils\build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\torch\utils\cpp_extension.py", line 691, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\torch\utils\cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\datascience\anaconda3\envs\GracoNet-Object-Placement\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

I would really appreciate some direction! Thanks!

**Comment by benjaminwfriedman** [comment]
Seems like it was a windows issue. Worked fine on Ubuntu 18.04
